blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    BlogListView,
    BlogDetailView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_list"),
    path("detail/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from mailing.apps import MailingConfig
from mailing.views import (
    ClientListView,
    ClientCreateView,
    ClientUpdateView,
    ClientDetailView,
    ClientDeleteView,
    MailingListView,
    MailingDetailView,
    MailingCreateView,
    MailingUpdateView,
    MailingDeleteView,
    HomeView,
    MessageListView,
    MessageDetailView,
    MessageCreateView,
    MessageUpdateView,
    MessageDeleteView,
    LogListView,
    LogDetailView,
)


app_name = MailingConfig.name

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("client/", ClientListView.as_view(), name="client_list"),
    path("client/create/", ClientCreateView.as_view(), name="client_create"),
    path("client/update/<int:pk>/", ClientUpdateView.as_view(), name="client_update"),
    path("client/detail/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("client/delete/<int:pk>/", ClientDeleteView.as_view(), name="client_delete"),
    path("mailing/", MailingListView.as_view(), name="mailing_list"),
    path(
        "mailing/detail/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"
    ),
    path("mailing/create/", MailingCreateView.as_view(), name="mailing_create"),
    path(
        "mailing/update/<int:pk>/", MailingUpdateView.as_view(), name="mailing_update"
    ),
    path(
        "mailing/delete/<int:pk>/", MailingDeleteView.as_view(), name="mailing_delete"
    ),
    path("message/", MessageListView.as_view(), name="message_list"),
    path(
        "message/detail/<int:pk>/", MessageDetailView.as_view(), name="message_detail"
    ),
    path("message/create/", MessageCreateView.as_view(), name="message_create"),
    path(
        "message/update/<int:pk>/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "message/delete/<int:pk>/", MessageDeleteView.as_view(), name="message_delete"
    ),
    path("log/", LogListView.as_view(), name="log_list"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.apps import UsersConfig
from users.views import (
    UserCreateView,
    email_verification,
    GeneratePasswordView,
    ProfileView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("password-reset/", GeneratePasswordView.as_view(), name="password-reset"),
    path("profile/", ProfileView.as_view(), name="profile"),
]

mailing/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Client(models.Model):
    email = models.EmailField(
        unique=True,
        verbose_name="Электронная почта",
        help_text="Укажите электронную почту",
    )
    full_name = models.CharField(
        max_length=100, verbose_name="Ф.И.О", help_text="Укажите Ф.И.О."
    )
    comment = models.TextField(
        verbose_name="Комментрарий", help_text="Напишите комментарий", **NULLABLE
    )

    user = models.ForeignKey(
        User, verbose_name="Пользователь", on_delete=models.SET_NULL, **NULLABLE
    )

    class Meta:
        verbose_name = "Клиент сервиса"
        verbose_name_plural = "Клиенты сервиса"
        ordering = ("full_name",)

    def __str__(self):
        return self.full_name


class Message(models.Model):

    title = models.CharField(
        max_length=255, verbose_name="Тема письма", help_text="Укажите тему письма"
    )
    message = models.TextField(
        verbose_name="Сообщение", help_text="Введите текст сообщения"
    )
    user = models.ForeignKey(
        User, verbose_name="Пользователь", on_delete=models.CASCADE, **NULLABLE
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"


class Mailing(models.Model):

    DAILY = "Раз в день"
    WEEKLY = "Раз в неделю"
    MONTHLY = "Раз в месяц"

    frequency = [
        (DAILY, "Раз в день"),
        (WEEKLY, "Раз в неделю"),
        (MONTHLY, "Раз в месяц"),
    ]

    CREATED = "Создана"
    STARTED = "Запущена"
    COMPLETED = "Завершена"

    mailing_status = [
        (CREATED, "Создана"),
        (STARTED, "Запущена"),
        (COMPLETED, "Завершена"),
    ]

    name = models.CharField(max_length=150, verbose_name="Название")
    description = models.TextField(**NULLABLE, verbose_name="Описание")
    status = models.CharField(
        max_length=150,
        choices=mailing_status,
        default=CREATED,
        verbose_name="Статус рассылки",
    )
    periodicity = models.CharField(
        max_length=150,
        choices=frequency,
        default=DAILY,
        verbose_name="Периодичность рассылки",
    )
    start_date = models.DateTimeField(
        verbose_name="Дата начала", **NULLABLE, help_text="Укажите дату начала рассылки"
    )
    end_date = models.DateTimeField(
        verbose_name="Дата окончания",
        **NULLABLE,
        help_text="Укажите дату окончания рассылки",
    )
    next_send_time = models.DateTimeField(
        verbose_name="Время следующей отправки", **NULLABLE
    )
    clients = models.ManyToManyField(
        Client,
        related_name="mailing",
        verbose_name="Выберите клиентов, которым будет отправлена рассылка",
    )
    message = models.ForeignKey(
        Message,
        verbose_name="Cообщение",
        help_text="Укажите текст сообщения",
        on_delete=models.CASCADE,
        **NULLABLE,
    )
    user = models.ForeignKey(
        User, verbose_name="Пользователь", on_delete=models.CASCADE, **NULLABLE
    )

    def __str__(self):
        return f"{self.name}, статус: {self.status}"

    def save(self, *args, **kwargs):
        if not self.next_send_time:
            self.next_send_time = self.start_date
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ("name",)
        permissions = [
            ("deactivate_mailing", "Can deactivate mailing"),
            ("view_all_mailings", "Can view all mailings"),
        ]


class Log(models.Model):

    SUCCESS = "Успешно"
    FAIL = "Неуспешно"

    attempt_status = [
        (SUCCESS, "Успешно"),
        (FAIL, "Неуспешно"),
    ]

    time = models.DateTimeField(
        verbose_name="Дата и время попытки отправки", auto_now_add=True
    )
    status = models.CharField(
        max_length=50, choices=attempt_status, verbose_name="Cтатус рассылки"
    )
    server_response = models.CharField(
        max_length=150, verbose_name="Ответ почтового сервера", **NULLABLE
    )
    mailing = models.ForeignKey(
        Mailing, on_delete=models.CASCADE, verbose_name="Рассылка"
    )

    def __str__(self):
        return f"{self.mailing} {self.time} {self.status} {self.server_response}"

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылки"

mailing/forms.py
from django.forms import ModelForm

from mailing.models import Client, Message, Mailing


class StyleFormsMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class ClientForm(StyleFormsMixin, ModelForm):
    class Meta:
        model = Client
        exclude = ("owner",)


class MessageForm(StyleFormsMixin, ModelForm):
    class Meta:
        model = Message
        exclude = ("owner",)


class MailingForm(StyleFormsMixin, ModelForm):
    class Meta:
        model = Mailing
        exclude = [
            "owner",
        ]

mailing/views.py
from datetime import datetime

import smtplib
from random import sample

import pytz
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.http import Http404
from django.shortcuts import redirect

from django.urls import reverse_lazy, reverse
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.core.mail import send_mail

from blog.models import Blog
from mailing.forms import ClientForm, MailingForm, MessageForm
from mailing.models import Client, Mailing, Log, Message


class HomeView(TemplateView):
    template_name = "mailing/home.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = "Главная"
        context_data["count_mailing"] = len(Mailing.objects.all())
        count_active_mailings = Mailing.objects.filter().count()
        context_data["count_active_mailings"] = count_active_mailings
        unique_clients_count = Client.objects.filter().distinct().count()
        context_data["count_unique_clients"] = unique_clients_count
        all_posts = list(Blog.objects.filter())
        context_data["random_blog_posts"] = sample(all_posts, min(3, len(all_posts)))
        return context_data


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = "mailing/client_list.html"

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name="manager"):
            queryset = queryset.filter(user=self.request.user)
        return queryset


class ClientDetailView(DetailView):
    model = Client
    template_name = "mailing/client_detail.html"


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("mailing:client_list")

    def form_valid(self, form):
        new_client = form.save()
        if new_client.user is None:
            new_client.user = self.request.user
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("mailing:client_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy("mailing:client_list")


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = "Рассылки"
        return context_data

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name="manager"):
            queryset = queryset.filter(user=self.request.user)
        return queryset


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = "Создать рассылку"
        return context_data

    def get_success_url(self):
        return reverse("mailing:mailing_list")

    def form_valid(self, form):
        new_mailing = form.save()
        new_mailing.owner = self.request.user
        new_mailing.save()
        return super().form_valid(form)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    template_name = "mailing/mailing_detail.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if settings.CACHE_ENABLED:
            key = f"log_list_{self.object.pk}"
            log_list = cache.get(key)
            if log_list is None:
                log_list = self.object.log_set.all()
                cache.set(key, log_list)
        else:
            log_list = self.object.log_set.all()
        context_data["logs"] = log_list

        return context_data


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = "Обновить рассылку"
        return context_data


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy("mailing:mailing_list")

    login_url = "users:login"
    redirect_field_name = "redirect_to"


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def form_valid(self, form):
        new_message = form.save()
        new_message.owner = self.request.user
        new_message.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = "Создание сообщения"
        return context_data


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = f"Сообщения"
        return context_data

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name="manager"):
            queryset = queryset.filter(user=self.request.user)
        return queryset


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = f'Редактирование "{self.object.title}"'
        return context_data


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy("mailing:message_list")

    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = "Удаление сообщения"
        return context_data


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = "Детали сообщения"
        return context_data


class LogListView(LoginRequiredMixin, ListView):
    model = Log
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = f"Логи"
        return context_data


class LogDetailView(LoginRequiredMixin, DetailView):
    model = Log

mailing/templates/mailing/base.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">
    {% include 'mailing/includes/inc_menu.html' %}
    {% block content %}
    {% endblock %}
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-8">{{ title }}</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
                <div class="col-12">
                    <div class="row">
                        <div class="col-8">
                            <div class="card">
                                <div class="card-body">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <p>Хотите удалить клиента "{{ object.email }}"?</p>
                                        <button type="submit" class="btn btn-lg btn-block btn-outline-danger">Удалить
                                        </button>
                                    </form>
                                    <a href="{% url 'mailing:client_list' %}"
                                       class="btn btn-lg btn-block btn-outline-warning">Отмена</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col-md-7">
                <div class="card-body">
                    <p class="card-text">{{ object.full_name }}</p>
                    <p class="card-text"> {{ object.email }} </p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'mailing:client_list' %}"
                               class="btn btn-md btn-block btn-outline-secondary"> Назад </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html'%}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-6 fw-bold">Список получателей рассылки</h1>
</div>

<div class="container text-center">
    <div class="row">
        <div class="col-4">
            <a type="button" class="btn-lg btn-success mx-1" href="{% url 'mailing:client_create' %}">Добавить
                получателей</a>
        </div>
    </div>
</div>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for client in object_list %}
    <div class="col-5 p-1">
        <div class="card shadow-sm">
            <div class="card-body">
                <p class="card-text">Имя: {{ client.full_name }}</p>
                <p class="card-text">Email: {{ client.email }}</p>
                <p class="card-text">Комментарий: {{ client.comment }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% if user == client.user or user.is_superuser %}
                        <a class="btn btn-outline-success" href="{% url 'mailing:client_detail' client.pk %}" role="button">Просмотр</a>
                        <a class="btn btn-outline-success" href="{% url 'mailing:client_update' client.pk %}"
                           role="button">Редактировать</a>
                        <a class="btn btn-outline-danger" href="{% url 'mailing:client_delete' client.pk %}" role="button">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

<div class="d-grid gap-2 col-3 mx-auto">
    {% if user.is_authenticated %}
    <a type="button" class="btn btn-success btn-lg" href="{% url 'mailing:mailing_list' %}"> Личный кабинет пользователя</a>
    {% else %}
     <a type="button" class="btn btn-success btn-lg" href="{% url 'users:register' %}">Попробовать бесплатно</a>
    {% endif %}
</div>


    <div class="row">
        <div class="col-12">
            <ul class="list-group px-3 py-3 pt-md-5 pb-md-4 mx-auto ml-auto">
                <h3><li class="list-group-item d-flex justify-content-between align-items-center">
                    Создано рассылок:
                    <span class="badge bg-success rounded-pill">{{ count_mailing }}</span>
                </li></h3>
                <h3><li class="list-group-item d-flex justify-content-between align-items-center">
                    Количество активных рассылок:
                    <span class="badge bg-success rounded-pill">{{ count_active_mailings }}</span>
                </li></h3>
                <h3><li class="list-group-item d-flex justify-content-between align-items-center">
                    Количество уникальных клиентов:
                    <span class="badge bg-success rounded-pill">{{ count_unique_clients }}</span>
                </li></h3>
            </ul>
        </div>
    </div>

    <div class="row text-center">
        {% for blog in random_blog_posts %}
            <div class="col-4">
                <div class="card mb-4 box-shadow">
                    <img class="rounded"
                         style='width: 300px;height: 300px;overflow: hidden;margin: 20px; object-fit: contain'
                         alt="Image"
                         src="/media/{{ blog.image }}"/>
                    <div class="card-body">
                        <h3 class="card-title pricing-card-title">{{ blog }}</h3>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <p>{{ blog.text|truncatechars:100 }}</p>
                        </ul>
                        <a href="{% url 'blog:blog_detail' blog.pk %}" type="button"
                           class="btn btn-primary btn-block btn-outline-dark mt-auto">Подробнее</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}

{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h4 class="display-4">{{ object.name }}</h4>
</div>
<main>
    <div class="card text-center">
        <div class="card-header">
            <h5>Информация о рассылке</h5>
        </div>
        <div class="card-body">
            <p class="card-text">Статус рассылки: {{ object.status }}</p>
            <p class="card-text">Периодичность рассылки: {{ object.periodicity }}</p>
            <p class="card-text">Дата начала: {{ object.start_date }}</p>
            <p class="card-text">Дата окончания: {{ object.end_date }}</p>
            <p class="card-text">Время следующей отправки: {{ object.next_send_time }}</p>
            <p class="card-text">Cообщение: {{ object.message }}</p>
        </div>
    </div>
</main>

<div class="card-footer">
    <div class="btn-group">
        <a href="{% url 'mailing:mailing_update' object.pk %}"
           class="btn btn-md btn-block btn-outline-success"> Редактировать </a>
    </div>
    <div class="btn-group">
        <a href="{% url 'mailing:mailing_delete' object.pk %}"
           class="btn btn-md btn-block btn-outline-danger"> Удалить </a>
    </div>
    <div class="btn-group">
        <a href="{% url 'mailing:mailing_list' %}"
           class="btn btn-md btn-block btn-outline-warning"> Назад </a>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}
{% block content %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-6 fw-bold">Личный кабинет пользователя</h1>
</div>

<div class="container text-center">
    <div class="row">
         <div class="col-4">
            <a type="button" class="btn-lg btn-success" href="{% url 'mailing:mailing_create' %}">Создать рассылку</a>
        </div>
        <div class="col-4">
            <a type="button" class="btn-lg btn-success" href="{% url 'mailing:message_create' %}">Создать
                сообщение</a>
        </div>
        <div class="col-4">
            <a type="button" class="btn-lg btn-success mx-1" href="{% url 'mailing:client_create' %}">Добавить
                получателей</a>
        </div>
    </div>
</div>

<div class="container text-center">
    <div class="row">
         <div class="col-4">
            <a type="button" class="btn-lg btn-outline-success" href="{% url 'mailing:log_list' %}">Попытки рассылки</a>
        </div>
        <div class="col-4">
            <a type="button" class="btn-lg btn-outline-success" href="{% url 'mailing:message_list' %}">Мои
                сообщения</a>
        </div>
        <div class="col-4">
            <a type="button" class="btn-lg btn-outline-success" href="{% url 'mailing:client_list' %}">Мои
                получатели</a>
        </div>
    </div>
</div>

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ object.name }}</p>
                        <p class="card-text">Статус рассылки: {{ object.status }}</p>
                        <p class="card-text">Периодичность рассылки: {{ object.periodicity }}</p>
                        <p class="card-text">Дата начала: {{ object.start_date }}</p>
                        <p class="card-text">Дата окончания: {{ object.end_date }}</p>
                        <p class="card-text">Время следующей отправки: {{ object.next_send_time }}</p>
                        <p class="card-text">Cообщение: {{ object.message }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'mailing:message_detail' object.pk %}"
                                   class="btn btn-outline-success">Посмотреть</a>
                                <a href="{% url 'mailing:message_update' object.pk %}"
                                   class="btn btn-outline-success">Редактировать</a>
                                <a href="{% url 'mailing:message_delete' object.pk %}"
                                   class="btn btn-outline-danger">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}

{% load my_tags %}
{% block content %}

<main>
    <div class="card text-center">
        <div class="card-header">
            <h5>{{ object.title }}</h5>
        </div>
        <div class="card-body">
            <p class="card-text">{{ object.message }}</p>
        </div>
    </div>
</main>

<div class="card-footer">
    <div class="btn-group">
        <a href="{% url 'mailing:message_update' object.pk %}"
           class="btn btn-md btn-block btn-outline-success"> Редактировать </a>
    </div>
    <div class="btn-group">
        <a href="{% url 'mailing:message_delete' object.pk %}"
           class="btn btn-md btn-block btn-outline-danger"> Удалить </a>
    </div>
    <div class="btn-group">
        <a href="{% url 'mailing:message_list' %}"
           class="btn btn-md btn-block btn-outline-warning"> Назад </a>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-6 fw-bold">Сообщения</h1>
</div>

<div class="container text-center">
    <div class="row">
        <div class="col-4">
            <a type="button" class="btn-lg btn-success" href="{% url 'mailing:message_create' %}">Создать
                новое сообщение</a>
        </div>
    </div>
</div>

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ object.title }}</p>
                        <p class="card-text">{{ object.message|truncatechars:150 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'mailing:message_detail' object.pk %}"
                                   class="btn btn-outline-success">Посмотреть</a>
                                <a href="{% url 'mailing:message_update' object.pk %}"
                                   class="btn btn-outline-success">Редактировать</a>
                                <a href="{% url 'mailing:message_delete' object.pk %}"
                                   class="btn btn-outline-danger">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}