blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    BlogListView,
    BlogDetailView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_list"),
    path("detail/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Blog(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name="Заголовок",
        help_text="Введите заголовок",
    )
    slug = models.CharField(
        max_length=60, verbose_name="slug", help_text="Введите slug", **NULLABLE
    )
    content = models.TextField(
        verbose_name="Текст", help_text="Введите текст", **NULLABLE
    )
    image = models.ImageField(
        upload_to="blogs/",
        verbose_name="Изображение",
        help_text="Загрузите изображение",
        **NULLABLE
    )
    created_at = models.DateField(auto_now_add=True)
    is_published = models.BooleanField(
        verbose_name="Публикация", help_text="Укажите статус публикации", default=True
    )
    views_count = models.PositiveIntegerField(
        verbose_name="Просмотры", help_text="Количество просмотров", default=0
    )

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from blog.models import Blog


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = (
            "title",
            "content",
            "image",
        )

blog/views.py
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from blog.models import Blog


class SetSlugMixin:
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.slug = slugify(obj.title)
        obj.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col-md-7">
                <div class="card shadow-sm">
                    <img src="{{ object.image | media_filter }}" class="img-fluid">
                    <div class="card-body">
                        <p class="card-text">{{ object.title }}</p>
                        <p class="card-text" > {{ object.content }} </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'blog:blog_list' %}"
                                   class="btn btn-md btn-block btn-outline-secondary"> Назад </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

<div
    class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
     <h1 class="display-8">Полезные статьи</h1>
</div>

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ object.image | media_filter }}" class="img-fluid">
                    <div class="card-body">
                        <p class="card-text">{{ object.title }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'blog:blog_detail' object.pk %}"
                                   class="btn btn-outline-success">Посмотреть</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}